FROM nvcr.io/nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-get update && apt-get install --no-install-recommends -y  \
    git wget sudo build-essential vim\
    python3 python3-setuptools python3-pip python3-dev python3-tk \
    ffmpeg libsm6 libxext6 && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install --no-install-recommends -y  \
    python3.8 && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2

RUN python3.8 -m pip install --upgrade pip


# Install dependencies
RUN pip --no-cache-dir install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

WORKDIR /workspace
RUN git clone https://github.com/ultralytics/ultralytics -b v8.1.24 /workspace && pip install --no-cache -e ".[export]"
RUN pip --no-cache-dir install lapx==0.5.5
RUN pip --no-cache-dir install tensorrt==8.5.3.1
RUN sed -i '166s/np.bool/bool/' /usr/local/lib/python3.8/dist-packages/tensorrt/__init__.py

ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/

ENV LANG C.UTF-8

RUN ln -svf /usr/bin/python3.8 /usr/bin/python
RUN pip --no-cache-dir install flask==3.0.3 onnxruntime-gpu==1.16.3